name: Monitor Roblox

on:
  schedule:
    # Executa a cada 3 minutos
    - cron: '*/3 * * * *'
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  monitor:
    concurrency:
      group: monitor-job
      cancel-in-progress: true # Cancela execução anterior se uma nova iniciar
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Timeout de 10 minutos para evitar execuções longas
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci --prefer-offline --no-audit --no-fund

      - run: node monitor.js
        env:
          S3_REGION: ${{ secrets.S3_REGION }}
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_KEY: ${{ secrets.S3_KEY }}
          S3_SECRET: ${{ secrets.S3_SECRET }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          PLAYERS: ${{ secrets.PLAYERS }}
          TZ_OFFSET_MINUTES: ${{ secrets.TZ_OFFSET_MINUTES }}
          ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
